import type { Skill } from '../types/skill';

export const skills: Skill[] = [
  {
    id: 'csharp',
    name: 'C#',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg',
    yearsOfExperience: 4,
    category: 'language',
  },
  {
    id: 'php',
    name: 'PHP',
    logo: 'https://cdn.simpleicons.org/php/777BB4',
    yearsOfExperience: 8,
    category: 'language',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    logo: 'https://cdn.simpleicons.org/typescript/3178C6',
    yearsOfExperience: 3,
    category: 'language',
  },
  {
    id: 'python',
    name: 'Python',
    logo: 'https://cdn.simpleicons.org/python/3776AB',
    yearsOfExperience: 8,
    category: 'language',
  },
  {
    id: 'golang',
    name: 'Golang',
    logo: 'https://cdn.simpleicons.org/go/00ADD8',
    yearsOfExperience: 3,
    category: 'language',
  },
  {
    id: 'powershell',
    name: 'PowerShell',
    logo: 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/ps_black_64.svg',
    yearsOfExperience: 4,
    category: 'language',
  },
  {
    id: 'bash',
    name: 'Bash',
    logo: 'https://cdn.simpleicons.org/gnubash/4EAA25',
    yearsOfExperience: 4,
    category: 'language',
  },
  {
    id: 'react',
    name: 'React',
    logo: 'https://cdn.simpleicons.org/react/61DAFB',
    yearsOfExperience: 2,
    category: 'framework',
  },
  {
    id: 'laravel',
    name: 'Laravel',
    logo: 'https://cdn.simpleicons.org/laravel/FF2D20',
    yearsOfExperience: 6,
    category: 'framework',
  },
  {
    id: 'dotnet',
    name: '.NET',
    logo: 'https://cdn.simpleicons.org/dotnet/512BD4',
    yearsOfExperience: 4,
    category: 'framework',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    logo: 'https://cdn.simpleicons.org/flutter/02569B',
    yearsOfExperience: 1,
    category: 'framework',
  },
  {
    id: 'git',
    name: 'Git',
    logo: 'https://cdn.simpleicons.org/git/F05032',
    yearsOfExperience: 8,
    category: 'tool',
  },
  {
    id: 'docker',
    name: 'Docker',
    logo: 'https://cdn.simpleicons.org/docker/2496ED',
    yearsOfExperience: 5,
    category: 'tool',
  },
  {
    id: 'terraform',
    name: 'Terraform',
    logo: 'https://cdn.simpleicons.org/terraform/7B42BC',
    yearsOfExperience: 2,
    category: 'tool',
  },
  {
    id: 'ansible',
    name: 'Ansible',
    logo: 'https://cdn.simpleicons.org/ansible/EE0000',
    yearsOfExperience: 2,
    category: 'tool',
  },
  {
    id: 'gitlab',
    name: 'GitLab CI',
    logo: 'https://cdn.simpleicons.org/gitlab/FC6D26',
    yearsOfExperience: 2,
    category: 'tool',
  },
  {
    id: 'gitops',
    name: 'GitOps',
    logo: 'https://cdn.simpleicons.org/argo/EF7B4D',
    yearsOfExperience: 1,
    category: 'tool',
  },
  {
    id: 'proxmox',
    name: 'Proxmox VE',
    logo: 'https://cdn.simpleicons.org/proxmox/E57000',
    yearsOfExperience: 3,
    category: 'tool',
  },
  {
    id: 'azure-devops',
    name: 'Azure DevOps',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azuredevops/azuredevops-original.svg',
    yearsOfExperience: 3,
    category: 'cloud',
  },
  {
    id: 'azure',
    name: 'Azure',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    yearsOfExperience: 3,
    category: 'cloud',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    logo: 'https://cdn.simpleicons.org/kubernetes/326CE5',
    yearsOfExperience: 2,
    category: 'cloud',
  },
  {
    id: 'aws',
    name: 'AWS',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
    yearsOfExperience: 1,
    category: 'cloud',
  },
  {
    id: 'oracle-cloud',
    name: 'Oracle Cloud',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
    yearsOfExperience: 5,
    category: 'cloud',
  },
  {
    id: 'mssql',
    name: 'MSSQL',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
    yearsOfExperience: 4,
    category: 'tool',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    logo: 'https://cdn.simpleicons.org/postgresql/4169E1',
    yearsOfExperience: 3,
    category: 'tool',
  },
  {
    id: 'elasticsearch',
    name: 'ElasticSearch',
    logo: 'https://cdn.simpleicons.org/elasticsearch/005571',
    yearsOfExperience: 3,
    category: 'tool',
  },
  {
    id: 'linux',
    name: 'Linux',
    logo: 'https://cdn.simpleicons.org/linux/FCC624',
    yearsOfExperience: 7,
    category: 'tool',
  },
  {
    id: 'windows',
    name: 'Windows',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/windows8/windows8-original.svg',
    yearsOfExperience: 5,
    category: 'tool',
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    logo: 'https://cdn.simpleicons.org/prometheus/E6522C',
    yearsOfExperience: 2,
    category: 'tool',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    logo: 'https://cdn.simpleicons.org/grafana/F46800',
    yearsOfExperience: 2,
    category: 'tool',
  },
  {
    id: 'app-insights',
    name: 'Application Insights',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
    yearsOfExperience: 2,
    category: 'tool',
  },
];

export const skillsByCategory = {
  languages: skills.filter((s) => s.category === 'language'),
  frameworks: skills.filter((s) => s.category === 'framework'),
  tools: skills.filter((s) => s.category === 'tool'),
  cloud: skills.filter((s) => s.category === 'cloud'),
};
