import type { WorkExperience } from '../types/work';

export const workExperiences: WorkExperience[] = [
  {
    id: 'work-1',
    title: 'DevOps Consultant',
    company: 'Business Logic s.r.o. & NSure s.r.o.',
    location: 'Czech Republic',
    startDate: new Date('2023-01-01'),
    endDate: 'present',
    description:
      'Currently serving as a DevOps Consultant for two companies, specializing in CI/CD process optimization and cloud infrastructure management.',
    highlights: [
      'Creating pipelines and optimizing CI/CD processes in Azure DevOps and GitLab CI',
      'Managing Windows and Linux servers in both on-premise and cloud environments',
      'Working with Azure Cloud services',
      'Operating and supporting applications running in Kubernetes, including Helm chart creation',
      'Automating infrastructure using Infrastructure as Code (IaC) tools (Terraform, ARM templates, Ansible)',
      'Web application development (ASP.NET Core, React)',
      'Developing automated scripts and tools (PowerShell, Python)',
      'Implementing logging and monitoring solutions for cloud-native applications and infrastructure components (Prometheus, Grafana, OTLP, ELK, Application Insights)',
      'Streamlining development workflows and deployment strategies',
      'Implementing DevOps best practices across the organization',
      'Installing and managing linux-based virtual servers (Ubuntu, AlmaLinux)',
    ],
    technologies: [
      'csharp',
      'react',
      'azure',
      'azure-devops',
      'kubernetes',
      'terraform',
      'postgresql',
      'powershell',
      'python',
      'docker',
      'ansible',
      'linux',
    ],
    notableExperiences: [
      'Migrated legacy applications based on .NET Framework and React from on-premise Windows servers to Azure App Service, improving scalability and reducing maintenance costs',
      'Implemented complete automation of bootstrapping and configuring fresh startup applications in .NET and React, reducing setup time from hours to minutes',
    ],
  },
  {
    id: 'work-2',
    title: 'DevOps Engineer',
    company: 'Business Logic s.r.o.',
    location: 'Czech Republic',
    startDate: new Date('2022-04-01'),
    endDate: new Date('2022-12-31'),
    description: 'Building and optimizing CI/CD pipelines and cloud infrastructure',
    highlights: [
      'Building and optimizing CI/CD pipelines',
      'Container orchestration with Kubernetes',
      'Azure cloud infrastructure management',
      'Deployment process automation',
      'System monitoring and optimization',
    ],
    technologies: ['csharp', 'azure-devops', 'kubernetes', 'docker', 'mssql', 'elasticsearch'],
    notableExperiences: [
      'Developed a centralized logging solution using the ELK stack for better monitoring and troubleshooting',
      'Migrated internal applications to Azure Kubernetes Service (AKS) for improved scalability and reliability',
    ],
  },
  {
    id: 'work-3',
    title: 'Software Developer',
    company: 'Business Logic s.r.o.',
    location: 'Czech Republic',
    startDate: new Date('2021-05-01'),
    endDate: new Date('2022-04-30'),
    description: 'Development of web APIs on the .NET platform',
    highlights: [
      'Development of web APIs on the .NET platform',
      'Foundational experience in backend development',
      'Enterprise-level application architecture',
    ],
    technologies: ['csharp', 'mssql'],
  },
];
